# -*- coding: utf-8 -*-
"""WordCloudScrapTitle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKu-YmmlFYXBHdJcL37YnMjbN5FmJM5v
"""

from os import removexattr
import requests
from bs4 import BeautifulSoup
import csv
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter

lista = []
url_list = []

url_list = [
#  2023
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/32',
#  2022
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/31',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/29',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/28',
#  2021
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/27',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/26',
#  2020
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/25',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/24',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/23',
#  2019
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/22',
#  2018
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/19',
#  2017
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/18',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/17',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/16',
#  2016
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/13',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/12',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/11',
#  2015
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/10',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/8',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/9',
#  2014
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/7',
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/6',
#  2013
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/4',
#  2012
  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/3',
#  2010
#  'https://eademfoco.cecierj.edu.br/index.php/Revista/issue/view/1'
    ]

for link in url_list:
  response = requests.get(link)
  soup = BeautifulSoup(response.content, 'html.parser')

  titulos = soup.find_all('h3', class_='title')

  for i in titulos:
    lista.append(i.get_text())

for i in range(len(lista)):
  lista[i] = lista[i].replace('\t', '').replace('\n', '').replace('Editorial', '').replace('Modelo de formatação dos artigos submetidos na Revista EaD em Foco', '')

ignorar = { 'de', 'para', 'com', 'a', 'o', 'os', 'as', 'que', 'e', 'na', 'nos' }
ocorrencias = Counter()
for linha in lista:
  ocorrencias.update(palavra for palavra in linha.split() if palavra not in ignorar)

unique_string=(" ").join(ocorrencias)
wordcloud = WordCloud(width = 1000, height = 500).generate(unique_string)
plt.figure(figsize=(15,8))
plt.imshow(wordcloud)
plt.axis("off")
plt.savefig("your_file_name"+".png", bbox_inches='tight')
plt.show()
plt.close()